### ISSUE TITLE
Jenkins: gerar pacote com itens de configuração do projeto ao fim de cada build

### ISSUE THREAD

**Issue by p-brz** [souzabrizolara/GCM#16]

**Comment by p-brz** [comment]
Verificar se é preciso fazer algo especial em relação à isso. Pois ao adicionar uma tag ao github (o q é feito a cada build) já é gerado um .zip com todos os arquivos versionados.

**Comment by abnt713** [comment]
Não é necessário, uma vez que todos os itens ficam disponíveis na plataforma do Github após cada nova build
