### ISSUE TITLE
Descrição da operação de débito

### ISSUE THREAD

**Issue by p-brz** [souzabrizolara/GCM#3]
**Solicitante**: cliente y

O cliente y solicita uma alteração na operação de débito para que seja informada uma descrição para esta operação. 
### Detalhamento

**Como** um usuário **eu quero** visualizar uma descrição da operação de débito **para que** eu não tenha dúvidas quanto ao significado da operação.
### Implementação
- Adicionar tooltip ao botão de débito.

**Comment by abnt713** [comment]
Validada por cliente Y
