### ISSUE TITLE
Crédito em poupança

### ISSUE THREAD

**Issue by p-brz** [souzabrizolara/GCM#5]
solicitante: cliente B

Cliente B solicitou uma nova funcionalidade ao sistema: crédito em poupança.
#### Subtarefas
- Criação de model e controller para poupança - issue #6
- Alteração da view para incluir operações de crédito e consulta da poupança - issue #9 
- Implementar operação de saldo da poupança no controller - issue #7 
- Implementar operação de crédito na poupança - issue #8

**Comment by abnt713** [comment]
Será necessário criar um novo Modelo para a entidade de Poupança. Para esta release, vamos implementar a funcionalidade de crédito e consulta. Futuramente, outras funcionalidades podem ser adicionadas em outras releases.
